-- 양청고등학교 특별실 예약 시스템
-- Supabase SQL Editor에서 한 번 실행합니다.

create extension if not exists btree_gist;


do $$ begin
  create type public.user_role as enum ('student', 'teacher', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.booking_status as enum ('pending', 'approved', 'rejected', 'cancelled', 'completed');
exception when duplicate_object then null; end $$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  email text not null unique,
  role public.user_role not null default 'student',
  grade smallint check (grade between 1 and 3),
  class_number smallint check (class_number between 1 and 30),
  student_number smallint check (student_number between 1 and 50),
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 100),
  location text not null check (char_length(location) between 1 and 120),
  capacity integer not null check (capacity > 0 and capacity <= 500),
  status text not null default 'available' check (status in ('available', 'unavailable')),
  description text not null default '',
  image_url text,
  available_start time not null default '08:00',
  available_end time not null default '18:00',
  max_booking_hours numeric(4,2) not null default 3 check (max_booking_hours > 0 and max_booking_hours <= 24),
  maintenance_mode boolean not null default false,
  closed_until timestamptz,
  created_at timestamptz not null default now(),
  constraint rooms_available_time_check check (available_start < available_end)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete restrict,
  user_id uuid not null references public.users(id) on delete restrict,
  approved_by uuid references public.users(id) on delete set null,
  purpose text not null check (char_length(purpose) between 2 and 500),
  people integer not null check (people > 0),
  start_time timestamptz not null,
  end_time timestamptz not null,
  status public.booking_status not null default 'pending',
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  cancelled_at timestamptz,
  constraint bookings_time_order check (start_time < end_time)
);

-- pending 요청도 시간대를 선점합니다. 동시 INSERT 경쟁은 DB가 원자적으로 차단합니다.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bookings_no_time_overlap'
      and conrelid = 'public.bookings'::regclass
  ) then
    alter table public.bookings
    add constraint bookings_no_time_overlap
    exclude using gist (
      room_id with =,
      tstzrange(start_time, end_time, '[)') with &&
    ) where (status in ('pending', 'approved'));
  end if;
end $$;

create index if not exists bookings_user_id_idx on public.bookings(user_id);
create index if not exists bookings_room_start_idx on public.bookings(room_id, start_time);
create index if not exists bookings_status_idx on public.bookings(status);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

create table if not exists public.booking_logs (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  action text not null,
  actor_id uuid references public.users(id) on delete set null,
  previous_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists booking_logs_booking_idx on public.booking_logs(booking_id, created_at desc);

-- RLS 재귀를 피하기 위한 권한 판정 함수입니다.
create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = auth.uid()
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('teacher', 'admin'), false)
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = 'admin', false)
$$;

create or replace function public.booking_blocks_daily_limit(target_status public.booking_status)
returns boolean
language sql
immutable
set search_path = public
as $$
  select target_status in ('pending', 'approved')
$$;

-- Google OAuth 최초 로그인 사용자를 학생으로 등록합니다.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, name, email, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    'student'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- 기존 Auth 사용자 중 프로필이 없는 계정을 보정합니다.
insert into public.users (id, name, email)
select id,
       coalesce(nullif(raw_user_meta_data ->> 'full_name', ''), split_part(email, '@', 1)),
       email
from auth.users
where email is not null
on conflict (id) do nothing;

create or replace function public.validate_booking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room public.rooms%rowtype;
  local_start timestamp;
  local_end timestamp;
  requested_hours numeric;
  daily_booked_hours numeric;
  day_start timestamptz;
  day_end timestamptz;
begin
  if new.status in ('rejected', 'cancelled', 'completed') then
    return new;
  end if;

  select * into target_room from public.rooms where id = new.room_id for share;
  if not found then raise exception using errcode = 'P0001', message = '존재하지 않는 특별실입니다.'; end if;

  local_start := new.start_time at time zone 'Asia/Seoul';
  local_end := new.end_time at time zone 'Asia/Seoul';

  if new.start_time >= new.end_time then
    raise exception using errcode = 'P0001', message = '종료 시간은 시작 시간보다 늦어야 합니다.';
  end if;
  if new.start_time <= now() then
    raise exception using errcode = 'P0001', message = '이미 지난 시간에는 예약할 수 없습니다.';
  end if;
  if local_start::date <> local_end::date then
    raise exception using errcode = 'P0001', message = '예약은 같은 날짜 안에서만 가능합니다.';
  end if;
  if local_start::time < target_room.available_start or local_end::time > target_room.available_end then
    raise exception using errcode = 'P0001', message = '특별실 이용 가능 시간을 벗어났습니다.';
  end if;
  requested_hours := extract(epoch from (new.end_time - new.start_time)) / 3600.0;
  day_start := local_start::date::timestamp at time zone 'Asia/Seoul';
  day_end := (local_start::date + 1)::timestamp at time zone 'Asia/Seoul';

  perform pg_advisory_xact_lock(
    hashtext(new.room_id::text),
    (local_start::date - date '2000-01-01')::integer
  );

  if tg_op = 'UPDATE' then
    select coalesce(sum(extract(epoch from (b.end_time - b.start_time)) / 3600.0), 0)
      into daily_booked_hours
    from public.bookings b
    where b.room_id = new.room_id
      and b.id <> old.id
      and public.booking_blocks_daily_limit(b.status)
      and b.start_time >= day_start
      and b.start_time < day_end;
  else
    select coalesce(sum(extract(epoch from (b.end_time - b.start_time)) / 3600.0), 0)
      into daily_booked_hours
    from public.bookings b
    where b.room_id = new.room_id
      and public.booking_blocks_daily_limit(b.status)
      and b.start_time >= day_start
      and b.start_time < day_end;
  end if;

  if daily_booked_hours + requested_hours > target_room.max_booking_hours then
    raise exception using errcode = 'P0001', message = '최대 예약 시간을 초과했습니다.';
  end if;
  if new.people > target_room.capacity then
    raise exception using errcode = 'P0001', message = '특별실 최대 수용 인원을 초과했습니다.';
  end if;
  if target_room.status <> 'available' or target_room.maintenance_mode then
    raise exception using errcode = 'P0001', message = '현재 점검 또는 이용 중지 상태인 특별실입니다.';
  end if;
  if target_room.closed_until is not null and target_room.closed_until > new.start_time then
    raise exception using errcode = 'P0001', message = '해당 시간에는 특별실이 일시 폐쇄 상태입니다.';
  end if;
  return new;
end;
$$;

create or replace function public.guard_booking_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  actor_role public.user_role := public.current_user_role();
  only_decision_changed boolean;
begin
  if auth.role() = 'service_role' then return new; end if;

  if tg_op = 'INSERT' then
    if actor is null or (new.user_id <> actor and actor_role <> 'admin') then
      raise exception using errcode = '42501', message = '다른 사용자의 예약을 생성할 수 없습니다.';
    end if;
    if actor_role in ('teacher', 'admin') then
      new.status := 'approved';
      new.approved_by := actor;
      new.approved_at := now();
    else
      new.status := 'pending';
      new.approved_by := null;
      new.approved_at := null;
    end if;
    return new;
  end if;

  if actor_role = 'admin' then
    if new.status = 'cancelled' and old.status <> 'cancelled' then new.cancelled_at := now(); end if;
    return new;
  end if;

  only_decision_changed :=
    new.room_id is not distinct from old.room_id and
    new.user_id is not distinct from old.user_id and
    new.purpose is not distinct from old.purpose and
    new.people is not distinct from old.people and
    new.start_time is not distinct from old.start_time and
    new.end_time is not distinct from old.end_time and
    new.created_at is not distinct from old.created_at and
    new.cancelled_at is not distinct from old.cancelled_at;

  if actor_role = 'teacher' and old.user_id <> actor then
    if old.status <> 'pending' or new.status not in ('approved', 'rejected') or not only_decision_changed then
      raise exception using errcode = '42501', message = '교사는 대기 중인 예약의 승인 또는 거절만 처리할 수 있습니다.';
    end if;
    new.approved_by := actor;
    new.approved_at := now();
    return new;
  end if;

  if old.user_id = actor then
    if old.status not in ('pending', 'approved') then
      raise exception using errcode = '42501', message = '처리 완료된 예약은 수정할 수 없습니다.';
    end if;
    if new.status = 'cancelled' then
      if new.room_id is distinct from old.room_id or
         new.user_id is distinct from old.user_id or
         new.purpose is distinct from old.purpose or
         new.people is distinct from old.people or
         new.start_time is distinct from old.start_time or
         new.end_time is distinct from old.end_time or
         new.created_at is distinct from old.created_at or
         new.approved_by is distinct from old.approved_by or
         new.approved_at is distinct from old.approved_at then
        raise exception using errcode = '42501', message = '예약 취소와 정보 변경을 동시에 처리할 수 없습니다.';
      end if;
      new.approved_by := old.approved_by;
      new.approved_at := old.approved_at;
      new.cancelled_at := now();
      return new;
    end if;
    if actor_role = 'student' and old.status = 'approved' then
      raise exception using errcode = '42501', message = '승인 완료된 예약은 수정할 수 없습니다. 변경이 필요하면 취소 후 다시 신청해 주세요.';
    end if;
    if new.status is distinct from old.status or
       new.user_id is distinct from old.user_id or
       new.approved_by is distinct from old.approved_by or
       new.approved_at is distinct from old.approved_at or
       new.cancelled_at is distinct from old.cancelled_at or
       new.created_at is distinct from old.created_at then
      raise exception using errcode = '42501', message = '예약 상태 또는 소유자는 직접 변경할 수 없습니다.';
    end if;
    return new;
  end if;

  raise exception using errcode = '42501', message = '예약을 변경할 권한이 없습니다.';
end;
$$;

drop trigger if exists bookings_guard_write on public.bookings;
create trigger bookings_guard_write
  before insert or update on public.bookings
  for each row execute function public.guard_booking_write();

drop trigger if exists bookings_validate on public.bookings;
create trigger bookings_validate
  before insert or update of room_id, people, start_time, end_time, status on public.bookings
  for each row execute function public.validate_booking();

create or replace function public.log_booking_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare action_name text;
begin
  if tg_op = 'INSERT' then action_name := 'created';
  elsif new.status = 'approved' and old.status <> 'approved' then action_name := 'approved';
  elsif new.status = 'rejected' and old.status <> 'rejected' then action_name := 'rejected';
  elsif new.status = 'cancelled' and old.status <> 'cancelled' then
    action_name := case when public.is_admin() and auth.uid() <> old.user_id then 'force_cancelled' else 'cancelled' end;
  else action_name := 'updated';
  end if;

  insert into public.booking_logs (booking_id, action, actor_id, previous_data, new_data)
  values (
    new.id,
    action_name,
    auth.uid(),
    case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
    to_jsonb(new)
  );
  return new;
end;
$$;

drop trigger if exists bookings_audit on public.bookings;
create trigger bookings_audit
  after insert or update on public.bookings
  for each row execute function public.log_booking_change();

create or replace function public.notify_booking_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare room_name text;
declare actor_role public.user_role := public.current_user_role();
begin
  if old.status is not distinct from new.status then return new; end if;
  select name into room_name from public.rooms where id = new.room_id;

  if new.status = 'approved' then
    insert into public.notifications(user_id, title, content)
    values (new.user_id, '예약이 승인되었습니다', room_name || ' 예약이 승인되었습니다.');
  elsif new.status = 'rejected' then
    insert into public.notifications(user_id, title, content)
    values (new.user_id, '예약이 거절되었습니다', room_name || ' 예약이 거절되었습니다.');
  elsif new.status = 'cancelled' then
    insert into public.notifications(user_id, title, content)
    values (
      new.user_id,
      case when actor_role = 'admin' and auth.uid() <> new.user_id then '예약이 강제 취소되었습니다' else '예약이 취소되었습니다' end,
      room_name || ' 예약이 취소되었습니다.'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_notify on public.bookings;
create trigger bookings_notify
  after update of status on public.bookings
  for each row execute function public.notify_booking_change();

-- pg_cron이 매분 호출하며 시작 10분 전 알림을 중복 없이 생성합니다.
create or replace function public.create_booking_reminders()
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.notifications(user_id, title, content)
  select b.user_id, '예약 시작 10분 전입니다',
         r.name || ' 예약이 ' || to_char(b.start_time at time zone 'Asia/Seoul', 'HH24:MI') || '에 시작됩니다.'
  from public.bookings b
  join public.rooms r on r.id = b.room_id
  where b.status = 'approved'
    and b.start_time > now() + interval '9 minutes'
    and b.start_time <= now() + interval '10 minutes'
    and not exists (
      select 1 from public.notifications n
      where n.user_id = b.user_id
        and n.title = '예약 시작 10분 전입니다'
        and n.content = r.name || ' 예약이 ' || to_char(b.start_time at time zone 'Asia/Seoul', 'HH24:MI') || '에 시작됩니다.'
        and n.created_at > now() - interval '30 minutes'
    );
$$;



-- 교사/관리자 전용 실제 DB 통계
create or replace function public.get_room_daily_booking_usage(
  target_room_id bigint,
  target_date date,
  exclude_booking_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room public.rooms%rowtype;
  day_start timestamptz := target_date::timestamp at time zone 'Asia/Seoul';
  day_end timestamptz := (target_date + 1)::timestamp at time zone 'Asia/Seoul';
  booked_hours numeric;
begin
  if auth.uid() is null then
    raise exception using errcode = '42501', message = '로그인이 필요합니다.';
  end if;

  select * into target_room from public.rooms where id = target_room_id;
  if not found then
    raise exception using errcode = 'P0001', message = '존재하지 않는 특별실입니다.';
  end if;

  select coalesce(sum(extract(epoch from (b.end_time - b.start_time)) / 3600.0), 0)
    into booked_hours
  from public.bookings b
  where b.room_id = target_room_id
    and public.booking_blocks_daily_limit(b.status)
    and (exclude_booking_id is null or b.id <> exclude_booking_id)
    and b.start_time >= day_start
    and b.start_time < day_end;

  return jsonb_build_object(
    'room_id', target_room.id,
    'date', target_date,
    'booked_hours', booked_hours,
    'max_booking_hours', target_room.max_booking_hours,
    'remaining_hours', greatest(target_room.max_booking_hours - booked_hours, 0)
  );
end;
$$;

create or replace function public.get_booking_statistics(target_month date default date_trunc('month', now())::date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if not public.is_staff() then
    raise exception using errcode = '42501', message = '통계를 조회할 권한이 없습니다.';
  end if;

  with bounds as (
    select target_month::timestamptz as from_at,
           (target_month + interval '1 month')::timestamptz as to_at
  ), monthly as (
    select count(*)::int total,
           count(*) filter (where status = 'approved')::int approved,
           count(*) filter (where status = 'cancelled')::int cancelled
    from public.bookings, bounds
    where start_time >= from_at and start_time < to_at
  ), room_usage as (
    select r.name,
           count(b.id)::int bookings,
           coalesce(round(sum(extract(epoch from (b.end_time - b.start_time)) / 3600)::numeric, 1), 0) hours,
           coalesce(round(least(
             100,
             (sum(extract(epoch from (b.end_time - b.start_time)) / 3600) /
               nullif(
                 (extract(epoch from (r.available_end - r.available_start)) / 3600) *
                 ((target_month + interval '1 month')::date - target_month),
                 0
               )) * 100
           )::numeric, 1), 0) usage_rate
    from public.rooms r
    left join public.bookings b on b.room_id = r.id and b.status in ('approved','completed')
      and b.start_time >= (select from_at from bounds) and b.start_time < (select to_at from bounds)
    group by r.id, r.name, r.available_start, r.available_end order by hours desc
  ), grades as (
    select coalesce(u.grade::text, '미입력') grade, count(*)::int count
    from public.bookings b join public.users u on u.id = b.user_id, bounds
    where b.start_time >= from_at and b.start_time < to_at
    group by u.grade
  ), hourly_stats as (
    select
      to_char(start_time at time zone 'Asia/Seoul', 'HH24') as hour_of_day,
      count(*)::int as booking_count
    from public.bookings, bounds
    where start_time >= from_at and start_time < to_at
    group by hour_of_day
    order by hour_of_day
  ), trend as (
    select
      to_char(months.month_value, 'YYYY-MM') as month,
      count(b.id)::int as count
    from generate_series(
           date_trunc('month', target_month) - interval '5 months',
           date_trunc('month', target_month),
           interval '1 month'
         ) as months(month_value)
    left join public.bookings b
      on b.start_time >= months.month_value
     and b.start_time < months.month_value + interval '1 month'
    group by months.month_value
    order by months.month_value
  )
  select jsonb_build_object(
    'summary', (select jsonb_build_object(
      'total', total,
      'approved', approved,
      'cancelled', cancelled,
      'approval_rate', case when total = 0 then 0 else round(approved * 100.0 / total, 1) end,
      'cancellation_rate', case when total = 0 then 0 else round(cancelled * 100.0 / total, 1) end
    ) from monthly),
    'rooms', coalesce((select jsonb_agg(to_jsonb(ru)) from room_usage as ru), '[]'::jsonb),
    'grades', coalesce((select jsonb_agg(to_jsonb(g)) from grades as g), '[]'::jsonb),
    'hours', coalesce((select jsonb_agg(to_jsonb(h)) from hourly_stats as h), '[]'::jsonb),
    'trend', coalesce((select jsonb_agg(to_jsonb(t)) from trend as t), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.delete_room_if_no_active_bookings(target_room_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  blocking_count integer;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = '관리자만 특별실을 삭제할 수 있습니다.';
  end if;

  select count(*) into blocking_count
  from public.bookings
  where room_id = target_room_id
    and status = 'approved'
    and end_time > now();

  if blocking_count > 0 then
    raise exception using errcode = 'P0001', message = '승인된 예정 또는 진행 예약이 있는 특별실은 삭제할 수 없습니다. 먼저 예약을 취소해 주세요.';
  end if;

  delete from public.bookings
  where room_id = target_room_id;

  delete from public.rooms
  where id = target_room_id;

  if not found then
    raise exception using errcode = 'P0001', message = '존재하지 않는 특별실입니다.';
  end if;
end;
$$;

create or replace function public.delete_booking_as_admin(target_booking_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = '관리자만 예약 신청 내역을 삭제할 수 있습니다.';
  end if;

  delete from public.bookings
  where id = target_booking_id;

  if not found then
    raise exception using errcode = 'P0001', message = '존재하지 않는 예약입니다.';
  end if;
end;
$$;

-- Row Level Security
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.bookings enable row level security;
alter table public.notifications enable row level security;
alter table public.booking_logs enable row level security;

drop policy if exists "users_select_self_or_staff" on public.users;
create policy "users_select_self_or_staff" on public.users for select to authenticated
using (id = auth.uid() or public.is_staff());
drop policy if exists "users_update_admin" on public.users;
create policy "users_update_admin" on public.users for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "rooms_read_authenticated" on public.rooms;
create policy "rooms_read_authenticated" on public.rooms for select to authenticated using (true);
drop policy if exists "rooms_admin_insert" on public.rooms;
create policy "rooms_admin_insert" on public.rooms for insert to authenticated with check (public.is_admin());
drop policy if exists "rooms_admin_update" on public.rooms;
create policy "rooms_admin_update" on public.rooms for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "rooms_admin_delete" on public.rooms;
create policy "rooms_admin_delete" on public.rooms for delete to authenticated using (public.is_admin());

drop policy if exists "bookings_select_own_or_staff" on public.bookings;
create policy "bookings_select_own_or_staff" on public.bookings for select to authenticated
using (user_id = auth.uid() or public.is_staff());
drop policy if exists "bookings_insert_own" on public.bookings;
create policy "bookings_insert_own" on public.bookings for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists "bookings_update_own_or_staff" on public.bookings;
create policy "bookings_update_own_or_staff" on public.bookings for update to authenticated
using (user_id = auth.uid() or public.is_staff())
with check (user_id = auth.uid() or public.is_staff());

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications for select to authenticated
using (user_id = auth.uid());
drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "logs_select_owner_or_staff" on public.booking_logs;
create policy "logs_select_owner_or_staff" on public.booking_logs for select to authenticated
using (
  public.is_staff() or exists (
    select 1 from public.bookings b where b.id = booking_id and b.user_id = auth.uid()
  )
);

revoke all on function public.current_user_role() from public;
revoke all on function public.is_staff() from public;
revoke all on function public.is_admin() from public;
revoke all on function public.booking_blocks_daily_limit(public.booking_status) from public;
revoke all on function public.get_room_daily_booking_usage(bigint, date, bigint) from public;
revoke all on function public.delete_room_if_no_active_bookings(bigint) from public;
revoke all on function public.delete_booking_as_admin(bigint) from public;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.get_room_daily_booking_usage(bigint, date, bigint) to authenticated;
grant execute on function public.get_booking_statistics(date) to authenticated;
grant execute on function public.delete_room_if_no_active_bookings(bigint) to authenticated;
grant execute on function public.delete_booking_as_admin(bigint) to authenticated;
revoke all on function public.create_booking_reminders() from public;

-- 명시적 테이블 권한 + RLS의 이중 방어
grant select, update on public.users to authenticated;
grant select, insert, update, delete on public.rooms to authenticated;
grant select, insert, update on public.bookings to authenticated;
grant select, update on public.notifications to authenticated;
grant select on public.booking_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

select pg_notify('pgrst', 'reload schema');

-- Storage: 특별실 사진 공개 읽기, 관리자만 쓰기
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('room-images', 'room-images', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "room_images_public_read" on storage.objects;
create policy "room_images_public_read" on storage.objects for select
using (bucket_id = 'room-images');
drop policy if exists "room_images_admin_insert" on storage.objects;
create policy "room_images_admin_insert" on storage.objects for insert to authenticated
with check (bucket_id = 'room-images' and public.is_admin());
drop policy if exists "room_images_admin_update" on storage.objects;
create policy "room_images_admin_update" on storage.objects for update to authenticated
using (bucket_id = 'room-images' and public.is_admin())
with check (bucket_id = 'room-images' and public.is_admin());
drop policy if exists "room_images_admin_delete" on storage.objects;
create policy "room_images_admin_delete" on storage.objects for delete to authenticated
using (bucket_id = 'room-images' and public.is_admin());

-- Realtime publication 등록
do $$ begin
  alter publication supabase_realtime add table public.bookings;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.rooms;
exception when duplicate_object then null; end $$;
